# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Yodl' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Yodl
  pod 'AudioKit', '~> 4.0'
  pod 'Socket.IO-Client-Swift', '~> 15.2.0'
  target 'YodlTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'YodlUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
